<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>2f064e86-0e84-4cf5-a52f-0b3b4c373f7c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoxOffice.Flow\BoxOffice.Flow.csproj" />
  </ItemGroup>

</Project>
